spring:
  application:
    name: Tlias-Web-Management
  datasource:
    url: jdbc:mysql://localhost:3306/tlias-web-management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
